## Example bsdfan.toml config

# Optional delay in milliseconds (u64) 
# default is 2000 milliseconds (2 seconds)
#
# delay = 2000
#
# 
# Levels contains the set of all levels the fan will switch between 
# 
# num (i32) is the fan_level from 0 (idle) to 7/8 (max speed)
# Some thinkpads support 7 as max and some have 8 as max.
# Safest to just set max to 7, if you don't know for your device
#
# min (f32) is the temperature at which the program jumps back a level.
# max (f32) is the temperature at which the program jumps up a level.
#
# Can NOT repeat nums
# Placement order of nums doesn't matter, but max of the previous
# must be greater than the min of the next (once sorted) 
#


Levels = [
{num = 0, min =  0, max = 44}, 
{num = 1, min = 40, max = 48},
{num = 2, min = 44, max = 52},
{num = 3, min = 48, max = 56},
{num = 4, min = 52, max = 60},
{num = 5, min = 56, max = 64},
{num = 6, min = 60, max = 68},
{num = 7, min = 64, max = 32767},
]


# 
# Aliases are also set: 
#
# delay == delay_millis
# Levels == levels
# num == number || lvl || level
# min == min_temp || minimum
# max == max_temp || maximum
#

